services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - vaultwarden_data:/data
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=homelab-stack_traefik-net
      - traefik.http.routers.vaultwarden.rule=Host(`vault.aymn.systems`)
      - traefik.http.routers.vaultwarden.entrypoints=web
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

volumes:
  vaultwarden_data:
    external: true
    name: vaultwarden_vaultwarden_data

networks:
  traefik-net:
    name: homelab-stack_traefik-net
    external: true
