services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.aymn.systems
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab-stack_traefik-net"
      - "traefik.http.routers.homepage.rule=Host(`home.aymn.systems`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.routers.homepage.middlewares=homelab-basicauth@file"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  traefik-net:
    name: homelab-stack_traefik-net
    external: true
