- Homelab:
    - Homepage:
        href: https://home.aymn.systems
        description: This dashboard
        icon: homepage
    - Dockge:
        href: https://dockge.aymn.systems
        description: Docker stack manager
        icon: mdi-docker
    - Traefik:
        href: https://traefik.aymn.systems
        description: Reverse proxy dashboard
        icon: traefik

- Apps:
    - Immich:
        href: https://photos.aymn.systems
        description: Photo and video backup
        icon: immich
    - Navidrome:
        href: https://music.aymn.systems
        description: Music streaming
        icon: mdi-music

- Admin:
    - SSH:
        href: ssh://aym-n@100.79.113.109
        description: Tailscale admin access
        icon: mdi-console
