http:
  routers:
    hermes-router:
      rule: "Host(`hermes.aymn.systems`)"
      service: hermes-service
      entryPoints:
        - web
  services:
    hermes-service:
      loadBalancer:
        servers:
          - url: "http://hermes:8787"
