http:
  routers:
    nextcloud-router:
      rule: "Host(`cloud.aymn.systems`)"
      entryPoints:
        - web
      service: nextcloud-service
  services:
    nextcloud-service:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000"
